# Generated by Django 4.0.1 on 2022-01-28 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vigenere', '0005_rename_usedid_userandmessage_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userandmessage',
            name='Mess',
        ),
    ]
